apptodolist/urls.py
from django.urls import path
from . import views

# app_name is required here since we are using a project wide template (header.html).
# name = parameter that will match with the HTML macro.
app_name = 'app_todo'


urlpatterns = [
    # Starting url: /planner/
    path('',
         views.ListOfToDos.as_view(),
         name = 'app_todo'),

    # Patterns for lists
    path('<int:listid>/',
         views.ListOfToDoItems.as_view(),
         name = 'list'),
    path('add/',
         views.CreateList.as_view(),
         name='list_add'),
    path('<int:pk>/delete/',
         views.DeleteList.as_view(),
         name='list_delete'),

    # Patterns for items 
    path('<int:listid>/item/add/',
         views.CreateItem.as_view(),
         name='item_add'),
    path('<int:listid>/item/<int:pk>/',
         views.UpdateItem.as_view(),
         name='item_update'),
    path('<int:listid>/item/<int:pk>/delete/',
         views.DeleteItem.as_view(),
         name='item_delete'),
]

index_app/urls.py
from django.urls import path
from . import views

app_name = 'app_index'
urlpatterns = [
    path('', views.index, name='app_index')
]

plannerproject/urls.py
import debug_toolbar
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('index_app.urls', namespace='app_index')),
    path('planner/', include('apptodolist.urls', namespace='app_todo')),
    # path('applications/', include('job_tracker_app.urls', namespace='app_job')),
    path('pomodoro/', include('app_pomodoro.urls', namespace='app_pomodoro')),
    path('__debug__/', include(debug_toolbar.urls)),
]

apptodolist/models.py
from django.db import models
# from django.utils import timezone
from django.urls import reverse


# defining data models. these are superclasses extending to django.db.models.Model.
    # using models.Models to create superclasses giving a unique id field.
# requires 2 models:
    # 1. ToDoList (actual title),
    # 2. ToDoListItem (an individual entry in a list).

class ToDoList(models.Model):
    ''' This class is for each ToDoList title. '''

    list_name = models.CharField(max_length=100, unique = True)
    created_date = models.DateTimeField(auto_now_add=True)

    def get_absolute_url(self):
        ''' Returns the URL for the specific ToDoList. '''
        return reverse ('app_todo:list', args=[self.id])

    def __str__(self):
        return self.list_name

class ToDoListItem(models.Model):
    '''
    This class is for each individual item within a ToDoList.
    ---
    Status = Whether the item has been completed or not.
    '''

    list_name = models.ForeignKey(ToDoList, on_delete=models.CASCADE)
    item_name = models.CharField(max_length=100, unique = False)
    item_content = models.TextField(null=True, blank=True)
    created_date = models.DateTimeField(auto_now_add=True)
    status = models.BooleanField(default=False)

    def get_absolute_url(self):
        ''' Returns the URL for the specific ToDoListItem. '''
        return reverse('app_todo:item_update', args=[str(self.list_name.id), str(self.id)])

    def __str__(self):
        return f"{self.item_name}, from list: {self.list_name}"

apptodolist/views.py
from typing import Any
from django.urls import reverse, reverse_lazy
# from django.shortcuts import get_object_or_404 #, render, redirect
from django.views.generic import (
    ListView,
    CreateView,
    UpdateView,
    DeleteView,
)
from apptodolist.models import ToDoList, ToDoListItem


class ListOfToDos(ListView):
    model = ToDoList
    template_name = 'todo_index.html'


class ListOfToDoItems(ListView):
    model = ToDoListItem
    template_name = 'todo_items.html'

    def get_queryset(self):
        ''' 
        The self.kwargs['listid'] will be referenced within the urls.py file
        - The parameter will be the specific list (listid), as we do not want every
        single item created without a list filter.
        '''
        
        return ToDoListItem.objects.filter(list_name_id=self.kwargs['listid'])

    def get_context_data(self) -> dict[str, Any]:
        '''
        Function allows for adding to specific lists, rather than overwriting it.
        '''
        context = super().get_context_data()
        # list_name refers to the foreign key within ToDoListItem data model.
        context['list_name'] = ToDoList.objects.get(id=self.kwargs['listid'])
        return context


#CRUD Code below.
class CreateList(CreateView):
    model = ToDoList
    template_name = 'todo_list_add.html'
    fields = ['list_name']

    def get_context_data(self) -> dict[str, Any]:
        '''
        https://docs.djangoproject.com/en/5.0/topics/class-based-views/generic-display/#adding-extra-context
        '''
        context = super().get_context_data()
        context['list_name'] = 'Add a new list'
        return context

    def get_success_url(self):
        return reverse('app_todo:app_todo')


class CreateItem(CreateView):
    model = ToDoListItem
    template_name = 'todo_items_form.html'
    fields = [
        'list_name',
        'item_name',
        'item_content',
        'status',
    ]

    def get_initial(self):
        '''
        Returns a dictionary containing initial data for the form.
        - listid is from the ToDoList class (in Models), list_id_url method.
        - list_name ToDoList class property.

        '''
        initial_data = super().get_initial()
        list_name = ToDoList.objects.get(id=self.kwargs['listid'])
        initial_data['list_name'] = list_name
        return initial_data

    def get_context_data(self) -> dict[str, Any]:
        '''
        https://docs.djangoproject.com/en/5.0/topics/class-based-views/generic-display/#adding-extra-context
        '''
        context = super().get_context_data()
        list_name = ToDoList.objects.get(id=self.kwargs['listid'])
        context['list_name'] = list_name
        context['item_name'] = 'Create new item'
        return context

    def get_success_url(self):
        return reverse('app_todo:list', args=[self.object.list_name_id])


class UpdateItem(UpdateView):
    model = ToDoListItem
    template_name = 'todo_items_form.html'
    fields = [
        'list_name',
        'item_name',
        'item_content',
        'status',
    ]

    def get_context_data(self) -> dict[str, Any]:
        context = super().get_context_data()
        context['list_name'] = self.object.list_name
        context['item_name'] = 'Update item contents'
        return context

    def get_success_url(self):
        return reverse('app_todo:list', args=[self.object.list_name_id])


class DeleteList(DeleteView):
    model = ToDoList
    template_name = 'todo_list_delete.html'
    success_url = reverse_lazy('app_todo:app_todo')
    # Later potential feature:
    # can change the 'cancel' button to redirect to the list of items page, rather than index.


class DeleteItem(DeleteView):
    model = ToDoListItem
    template_name = 'todo_items_delete.html'

    def get_success_url(self):
        return reverse_lazy('app_todo:list', args=[self.kwargs['listid']])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['list_name'] = self.object.list_name
        return context
    

apptodolist/templates/todo_index.html
{% extends "header.html" %}

{% block title %}
    <h2><a href="{% url 'app_todo:app_todo' %}"> To Do List</a></h2>
{% endblock %}

{% block content %}

    {% if object_list %}
        <h3>Here are the current To Do Lists:</h3>
    {% endif %}

    <ul>
        {% for todolist in object_list %}
        <li>
            <div
                role="button"
                onclick="location.href='{% url "app_todo:list" todolist.id %}'">
                {{ todolist.list_name }}
            </div>
        </li>
        {% empty %}
        <h4>You currently do not have any lists to do.</h4>
    {% endfor %}
    </ul>

    <p>
        <input value="Add a new list" type="button"
        onclick="location.href='{% url "app_todo:list_add" %}'"/>
    </p>

{% endblock %}

apptodolist/templates/todo_items.html
{% extends "header.html" %}

{% block title %}
    <h2><a href="{% url 'app_todo:app_todo' %}"> To Do List</a></h2>
{% endblock %}

{% block content %}

    <h3>Edit current list: {{ list_name }}</h3>

    <ul>
        {% for item in object_list %}
        <li>
                <div role="button" onclick="location.href='{% url "app_todo:item_update" list_name.id item.id %}'"> 
                {{ item.item_name }}
                </div>
        </li>

        {% empty %}
        <h4>You currently do not have any items to do for this list.</h4>
        {% endfor %}
    </ul>

    <p>
        <input value="Add a new item"
        type="button"
        onclick="location.href='{% url "app_todo:item_add" list_name.id %}';"/>

        <input value="Delete List" 
        type="button"
        onclick="location.href='{% url "app_todo:list_delete" list_name.id %}';"/>
    </p>

{% endblock %}

apptodolist/templates/todo_items_add.html
<html lang="en">

<head>
    <title> To Do Lists</title>
</head>


    <body>
        <h1>
            <a href="{% url 'app_index:app_index' %}"> Index Page</a>
        </h1>
    </div>
        <h2>
        <a href="{% url 'app_todo:app_todo' %}"> To Do Lists</a>
        </h2>
    </div>

    <h3>{{ list_name }}</h3>
    <div>
        <div>
            <form method="post">
                {% csrf_token %}
                <table>
                    {{ form.as_table }}
                </table>
                <input type="submit" value="Submit">
                <input value="Cancel" type="button" onclick="location.href='{% url "app_todo:list" list_name.id %}'">
            </form>
        </div>
    </div>

apptodolist/templates/todo_items_delete.html
{% extends "header.html" %}

{% block title %}
    <h2><a href="{% url 'app_todo:app_todo' %}"> To Do List</a></h2>
{% endblock %}

{% block content %}

    <h3>Delete To-Do Item</h3>

    <p>
        Are you sure you want to delete this item?
    </p>
        From List Name: {{object.list_name}}
    <p>
        Item to delete: {{object.item_name}}
    </p>

    <form method="POST">
        {% csrf_token %}
        <input value="Delete" type="submit">
        <input value="Cancel" type="button" onclick="location.href='{% url "app_todo:list" list_name.id %}';"/>
    </form>

{% endblock %}

apptodolist/templates/todo_items_form.html
{% extends "header.html" %}

{% block title %}
    <h2><a href="{% url 'app_todo:app_todo' %}"> To Do List</a></h2>
{% endblock %}

{% block content %}

    <h3>{{ list_name }}</h3>

    <form method="post">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input value="Submit" type="submit"/>
        
        <input value="Cancel" type="button" onclick="location.href='{% url "app_todo:list" list_name.id %}'"/>

        {% if object %}
        <input value="Delete Item" type="button" onclick="location.href='{% url "app_todo:item_delete" list_name.id object.id %}'"/>
        {% endif %}
    </form>

{% endblock %}

apptodolist/templates/todo_list_add.html
{% extends "header.html" %}

{% block title %}
    <h2><a href="{% url 'app_todo:app_todo' %}"> To Do List</a></h2>
{% endblock %}

{% block content %}

    <h3>{{ list_name }}</h3>
    <div>
        <div>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <input value="Save" type="submit">
                <input value="Cancel" type="button" onclick="location.href='{% url "app_todo:app_todo" %}';">
            </form>
        </div>
    </div>

{% endblock %}

apptodolist/templates/todo_list_delete.html
{% extends "header.html" %}

{% block title %}
    <h2><a href="{% url 'app_todo:app_todo' %}"> To Do List</a></h2>
{% endblock %}

{% block content %}

    <h3>Delete To-Do List</h3>
    </div>

    <p>
        Are you sure you want to delete this list?
    </p>
    <p>
        {{object.list_name}}
    </p>

    <form method="POST">
        {% csrf_token %}
        <input value="Delete" type="submit">
        <input value="Cancel" type="button" onclick="location.href='{% url "app_todo:app_todo" %}';"/>
    </form>

{% endblock %}

apptodolist/templates/todoindex.html
<html lang="en">

<head>
    <title> To Do Lists</title>
</head>


    <body>
        <h1>
            <a href="{% url 'app_index:app_index' %}"> Index Page</a>
        </h1>
    </div>
        <h2>
        <a href="{% url 'app_todo:app_todo' %}"> To Do Lists</a>
        </h2>
    </div>
    {% if object_list%}
    <h3>Here are the current To Do Lists.</h3>
    {% endif %}
    <ul>
        {% for todolist in object_list %}
        <li>
            <div
                role="button"
                onclick="location.href='{% url "app_todo:list" todolist.id %}'">
                {{ todolist.list_name }}
            </div>
        </li>

        {% empty %}
        <h4>You currently do not have any lists to do.</h4>
        {% endfor %}

    </ul>
    </body>
</html>

apptodolist/templates/todoitems.html
<html lang="en">

<head>
    <title>To Do List Item</title>
</head>


    <body>
        <h1>
            <a href="{% url 'app_index:app_index' %}"> Index Page</a>
        </h1>
    </div>
        <h2>
        <a href="{% url 'app_todo:app_todo' %}"> To Do Lists</a>
        </h2>
    </div>

    <h3>Edit current list: {{ list_name }}</h3>
    </div>
    
    <ul>
        {% for item in object_list %}
        <li>
            <div>
                <div role="button" onclick="location.href='{% url "app_todo:list" item.id}'"> 
                {{ item.item_name }}

                </div>
            </div>
        </li>

        {% empty %}
        <h4>You currently do not have any items to do for this list.</h4>
        {% endfor %}

    </ul>
    </body>
</html>