app_pomodoro/urls.py
from django.urls import path
# from .views import pomodoro
from .views import timer_view

app_name = 'app_pomodoro'

urlpatterns = [
    # path('', pomodoro, name='app_pomodoro'),
    path('', timer_view, name='app_pomodoro'),
]

apptodolist/urls.py
from django.urls import path
from . import views

# app_name is required here since we are using a project wide template (header.html).
# name = parameter that will match with the HTML macro.
app_name = 'app_todo'


urlpatterns = [
    # Starting url: /planner/
    path('',
         views.ListOfToDos.as_view(),
         name = 'app_todo'),

    # Patterns for lists
    path('<int:listid>/',
         views.ListOfToDoItems.as_view(),
         name = 'list'),
    path('add/',
         views.CreateList.as_view(),
         name='list_add'),
    path('<int:pk>/delete/',
         views.DeleteList.as_view(),
         name='list_delete'),

    # Patterns for items 
    path('<int:listid>/item/add/',
         views.CreateItem.as_view(),
         name='item_add'),
    path('<int:listid>/item/<int:pk>/',
         views.UpdateItem.as_view(),
         name='item_update'),
    path('<int:listid>/item/<int:pk>/delete/',
         views.DeleteItem.as_view(),
         name='item_delete'),
]

index_app/urls.py
from django.urls import path
from . import views

app_name = 'app_index'
urlpatterns = [
    path('', views.index, name='app_index')
]

plannerproject/urls.py
import debug_toolbar
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('index_app.urls', namespace='app_index')),
    path('planner/', include('apptodolist.urls', namespace='app_todo')),
    # path('applications/', include('job_tracker_app.urls', namespace='app_job')),
    path('pomodoro/', include('app_pomodoro.urls', namespace='app_pomodoro')),
    path('__debug__/', include(debug_toolbar.urls)),
]

plannerproject/templates/header.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Organiser</title>
    <link rel="stylesheet" href="{% static 'plannerproject/style.css' %}">
</head>


<body>
    <div class="headers">
        <h1>
            <a href="{% url 'app_index:app_index' %}"> Brain</a>
        </h1>
    </div>

    <div class="tabs">
    <tr><a href="{% url 'app_todo:app_todo' %}"> To Do List</a></tr>
    <tr><a href="{% url 'app_pomodoro:app_pomodoro' %}"> Pomodoro</a></tr>

    </div>

    {% block title %}
    <!--title of the application will be replaced for each page/ application here-->
    {% endblock %}

    {% block content %}
    <!--content will be replaced for each page here-->
    {% endblock %}

</body>
</html>